spring.application.name=lorekeeper-api

# PostgreSQL configuration
spring.datasource.url=jdbc:postgresql://localhost:5433/mydb
spring.datasource.username=niraj
spring.datasource.password=root

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# OpenLibrary API
lorekeeper.openlibrary.contact-email=your-email@example.com
