spring.application.name=lorekeeper-api
spring.datasource.url=jdbc:postgresql://localhost:5432/lorekeeper
spring.datasource.username=lorekeeper
spring.datasource.password=lorekeeper123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
